### ISSUE TITLE
About Stereo Evaluation

### ISSUE THREAD

**Issue by xiongqi123123** [qrzyang/UHP#2]
Hello author! I am a newcomer to deep learning and I apologize for seeking your help again. While reading your paper, I noticed that you used Stereo Evaluation as a visual evaluation metric. I have been researching the methods in the local toolkit MidDeEval3 provided by Stereo Evaluation for the past few days, but I have not been able to successfully reproduce your results. I would like to ask how you use Stereo Evaluation? If possible, I would greatly appreciate it. Thank you for your generous guidance！！！！！！！
![screenshot-1723771837801](https://github.com/user-attachments/assets/898d1a77-d950-4427-99f8-2ac0b676033b)

**Comment by xiongqi123123** [comment]
And when I use the save_diff_tofile function of test. py, I get an error saying "/home/coop 8/xxxxx/UHP/test. py", line 203, in save_disp_tofilefilename = sample["left_filename"][0].split('/')[-1]KeyError: 'left_filename'

**Comment by qrzyang** [comment]
Hello. This error map displays the results on the test set. As the test set lacks ground truth data, these visualizations are automatically generated by the KITTI website after submitting the predicted disparity. For reference, there is a similar function in the UHP/utils folder that can output error maps of the training set to tensorboard.

The KeyError issue seems to be caused by not recording the file name when reading images. You can try to debug the related files under the datasets folder.

In addition, we recommend that beginners try to reproduce more mature and concise code first, such as the supervised stereo matching method [PSMNet](https://github.com/JiaRenChang/PSMNet). These codes are more helpful for understanding and learning.

**Comment by xiongqi123123** [comment]
> Hello. This error map displays the results on the test set. As the test set lacks ground truth data, these visualizations are automatically generated by the KITTI website after submitting the predicted disparity. For reference, there is a similar function in the UHP/utils folder that can output error maps of the training set to tensorboard.
> 
> The KeyError issue seems to be caused by not recording the file name when reading images. You can try to debug the related files under the datasets folder.
> 
> In addition, we recommend that beginners try to reproduce more mature and concise code first, such as the supervised stereo matching method [PSMNet](https://github.com/JiaRenChang/PSMNet). These codes are more helpful for understanding and learning.

Very Very Thanks!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
